### ISSUE TITLE
k.type_string doesn't accept a newline char

### ISSUE THREAD

**Issue by parkerlreed** [SavinaRoja/PyUserInput#116]
The text input worked fine but the newline at the end threw an error. Linux.

```
[parker@stealth bin]$ python bar-scoket.py 
[+] Listening for connections on port: 2222
[+] Client connected: 192.168.0.179
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "bar-scoket.py", line 24, in run
    k.type_string(re.sub(r".*plr", "", self.data.replace('\r', '')))
  File "/usr/lib/python3.7/site-packages/pykeyboard/base.py", line 79, in type_string
    self.tap_key(char)
  File "/usr/lib/python3.7/site-packages/pykeyboard/base.py", line 43, in tap_key
    self.press_key(character)
  File "/usr/lib/python3.7/site-packages/pykeyboard/x11.py", line 76, in press_key
    self._handle_key(character, X.KeyPress)
  File "/usr/lib/python3.7/site-packages/pykeyboard/x11.py", line 68, in _handle_key
    keycode = self.lookup_character_keycode(character)
  File "/usr/lib/python3.7/site-packages/pykeyboard/x11.py", line 201, in lookup_character_keycode
    keysym = Xlib.XK.string_to_keysym(KEYSYMS[character])
KeyError: '\n'

vvv--- sent via xlib
ggfgg
```

**Comment by parkerlreed** [comment]
I see this is the old repo.
