### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0x9e in position 0: invalid start byte

### ISSUE THREAD

**Issue by fantasticguille** [SavinaRoja/PyUserInput#81]
System Data:
Ubuntu 14.04
Desktop KDE
Python 2.7.6
python-xlib installed
PyUserInput installed using pip install

I'm not being able to execute this sample test:
```python
from pymouse import PyMouse

m = PyMouse()
x = 100
y = 250
m.position() #gets mouse current position coordinates
m.move(x,y)
m.click(x,y) #the third argument "1" represents the mouse button
m.press(x,y) #mouse button press
m.release(x,y) #mouse button release
```
I'm getting a UnicodeDecodeError. This is my log:
```bash
Traceback (most recent call last):                                              
  File "test.py", line 6, in <module>                                           
    m = PyMouse()                                                               
  File "/usr/local/lib/python2.7/dist-packages/pymouse/x11.py", line 86, in __init__                                                                            
    self.display = Display(display)                                             
  File "/usr/lib/python2.7/dist-packages/Xlib/display.py", line 80, in __init__ 
    self.display = _BaseDisplay(display)                                        
  File "/usr/lib/python2.7/dist-packages/Xlib/display.py", line 62, in __init__
    display.Display.__init__(*(self, ) + args, **keys)
  File "/usr/lib/python2.7/dist-packages/Xlib/protocol/display.py", line 61, in __init__
    name, host, displayno)
  File "/usr/lib/python2.7/dist-packages/Xlib/support/connect.py", line 93, in get_auth
    return getattr(mod, modname).get_auth(sock, dname, host, dno)
  File "/usr/lib/python2.7/dist-packages/Xlib/support/unix_connect.py", line 116, in new_get_auth
    au = xauth.Xauthority()
  File "/usr/lib/python2.7/dist-packages/Xlib/xauth.py", line 84, in __init__
    self.entries.append((family, addr.decode('UTF-8'),
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x9e in position 0: invalid start byte
```
Anyone else had this error?
Please, any help or suggestion is welcome!

Thanks in forward.

**Comment by moses-palmer** [comment]
What does the following command yield? Run in a terminal:

    python -c "import os, Xlib.display; print(os.getenv('DISPLAY'));
 print(Xlib.display.Display())"

Can you run other Python applications that use *Python Xlib**?*

2016-01-22 4:10 GMT+01:00 Guille Acosta <notifications@github.com>:

**Comment by fantasticguille** [comment]
Thanks for your reply!

I ran that on terminal and this was the output:

```bash
root@c288:~# python -c "import os, Xlib.display; print(os.getenv('DISPLAY'));
> print(Xlib.display.Display())"
:50
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/usr/lib/python2.7/dist-packages/Xlib/display.py", line 80, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/lib/python2.7/dist-packages/Xlib/display.py", line 62, in __init__
    display.Display.__init__(*(self, ) + args, **keys)
  File "/usr/lib/python2.7/dist-packages/Xlib/protocol/display.py", line 61, in __init__
    name, host, displayno)
  File "/usr/lib/python2.7/dist-packages/Xlib/support/connect.py", line 93, in get_auth
    return getattr(mod, modname).get_auth(sock, dname, host, dno)
  File "/usr/lib/python2.7/dist-packages/Xlib/support/unix_connect.py", line 116, in new_get_auth
    au = xauth.Xauthority()
  File "/usr/lib/python2.7/dist-packages/Xlib/xauth.py", line 84, in __init__
    self.entries.append((family, addr.decode('UTF-8'),
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x9e in position 0: invalid start byte
```
This give you any idea?

Regards.

**Comment by fantasticguille** [comment]
@moses-palmer about the 2nd question, I'm not being able to install PyAutoGUI by using pip install.

The error cause that terminal shows me it's the same: 

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9e in position 0: invalid start byte

I can't figure out the consecuense, hope you can guide me with solution.

**Comment by moses-palmer** [comment]
The errors indicate that the problems that you experience are not related
to *PyUserInput*, but rather an *X* misconfiguration or unexpected machine
state.

The value for for the environment variable *$DISPLAY* seems rather high
(:50, on a normal desktop system it tends to be :0).

I don't know enough about the internals of *X* to offer you a solution, but
you may want to check the following:

   - Ensure that you run the terminal under a proper *X* session, and not
   connected through *SSH*.
   - Perhaps check your locale settings? The value of *$LANG*, especially
   the encoding part, could possibly affect how *Python Xlib* interprets
   data send over the socket.

I will close this issue, as it does not appear to be related to
*PyUserInput*. Good luck in finding out the root cause!

2016-01-22 21:32 GMT+01:00 Guille Acosta <notifications@github.com>:
